AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-payload specific exceptions:
#
Layout/ArgumentAlignment: { Exclude: ['spec/rust_payload_spec.rb'] }

# the placeholder API methods are meant to be empty
Style/EmptyMethod:
  Exclude:
    - 'lib/ronin/payloads/payload.rb'
    - 'spec/**/*'

# rubocop does not support constants that contain multiple numbers
Naming/ClassAndModuleCamelCase:
  AllowedNames:
    - X86_64

# robucop mistakes :x86_64 for a "symbol number"
Naming/VariableNumber:
  AllowedIdentifiers:
    - x86_64

# this is a bug in rubocop
Style/FormatStringToken:
  Exclude:
    - 'lib/ronin/payloads/builtin/cmd/powershell/reverse_shell.rb'
    - 'spec/builtin/cmd/powershell/reverse_shell_spec.rb'

# rubocop does not recognize empty-line continuations
Style/RedundantLineContinuation:
  Exclude:
    - 'lib/ronin/payloads/builtin/shellcode/**/*.rb'
Layout/LineContinuationSpacing:
  Exclude:
    - 'lib/ronin/payloads/builtin/shellcode/**/*.rb'
Style/StringConcatenation:
  Exclude:
    - 'lib/ronin/payloads/builtin/shellcode/**/*.rb'
